### ISSUE TITLE
GSETS not in sync with playdata

### ISSUE THREAD

**Issue by ivokwee** [bigomics/playbase#89]
1. The GSET.rda in the data folder in playbase is not the same as playdata::GSETS. 
2. Eventually, playbase::GSETS should be deprecated in favor of playdata::GSETS.
3. The use of iGSETS (GSETS with integer index) could be deprecated. Although iGSETS uses 100Mb and GSETS (with gene symbols) uses 1.4GB in memory. For memory reasons iGSETS would be preferable with accessor function getGSETS (as is now). This would reduce memory footprint. Needs to be done in playdata and playbase.

**Comment by mauromiguelm** [comment]
Hi Ivo,

**1 and 2:** playbase::GSETS, its likely a function that is not used anymore

![image](https://github.com/bigomics/playbase/assets/28757711/ae2c2f80-9320-4fef-a187-d09ac4b725b9)
![image](https://github.com/bigomics/playbase/assets/28757711/73bb5466-cf55-4884-93c0-f14873c236fb)


**3.** iGSETS uses way less memmory, I think its worth discussing and maybe implementing!
